= Mayfly Presentations

image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/mayflycd/mayfly-talks?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

Just want to view the presentations?
Go to: https://mayflycd.github.io/mayfly-talks

Want to see the sources?
Take a look in the `subprojects` directory for the specific presentations.

== Usage

The presentations are set-up with http://asciidoctor.org[Asciidoctor]
and generated to usable formats, like html5, with http://gradle.org[Gradle]
using the http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[asciidoctor-gradle-plugin].

To build the presentations run the following command:

....
$ ./gradlew presentation
....

Each presentation is a separate Gradle subproject, located within the `subprojects` directory.
To build only a specific presentation, run the following command:

....
$ ./gradlew :{name-of-subproject}:presentation
....

The generated presentation output can be found, per subproject, in the `build/asciidoc/{format}/`.

== Videos
Videos of Mayfly presentation
[https://twitter.com/mdirkse]Maarten Dirkse presented Mayfly @ the http://www.meetup.com/Docker-Randstad/[Docker Randstad meetup group] on August 20th, 2015: https://www.youtube.com/watch?v=r6oeVbTA6v8[video (35:55)]

== References

Links to handy resources for asciidoc presentations writing:

- http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
- http://asciidoctor.org/docs/asciidoc-writers-guide/
- https://github.com/asciidoctor/asciidoctor-reveal.js
- http://asciidoctor.org/docs/asciidoctor-gradle-plugin/
- https://github.com/asciidoctor/asciidoctor-diagram/
