= Mayfly

Provides each user story with:

- A feature branch
- Continuous Integration
- Virtual production-like environment
- Definition-of-Done

[NOTE.speaker]
--
So that's what Mayfly provides :)

For each user story, you get:

- a feature branch on the application repository
- continuous integration on the feature branch
- an environment for the user story based on the feature branch
- and a verification if the user story is
  production ready, according to the Definition of Done
--

== Everything-as-code

- Build pipelines as code
- Environments as code
- Definition-of-Done as code
- Tests as code

Teams in control; configuration is stored in the application repository.

[NOTE.speaker]
--
We do this by describing everything as code:

- we use the Jenkins JobDSL to
  configure the build pipeline as code
- we configure the environment as code
  in a deployment descriptor file
- we describe the Definition of Done as code
- and of course, you write tests for your code

All these files are stored in the code repository,
so it is always in-sync with the code it is for.
--

= Mayfly Principles

- `master` == production

[NOTE.speaker]
--
Our implementation for Continuous Delivery
strongly supports that the master branch of
your application should always represent the
state of your code in production.

If you diverge from that principle, the costs
of fixing issues increase since you'll be building
up technical debt against your production environment
--